name: Jira Cooperation Action

on:
  issues:
    types: [labeled]
  pull_request:
    branches:
      - develop

jobs:
  cooperate-issue:
    if: github.event.label.name == 'loadmap'
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Debug
        run: cat $GITHUB_EVENT_PATH

      - name: Get Cooperated Issue Number
        uses: actions/github-script@v6
        id: get-cooperated-issue-number
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const targetComment = comments.data.map((data) => data.body).find((body) => /JIRA-ISSUE-NUM=/.test(body))
            if (targetComment) {
              return targetComment.split('=')[1]
            }
            return 'cooperated'

      - name: Create Jira Issue
        uses: atlassian/gajira-create@v2.0.1
        # é€£æºæ¸ˆã¯ã‚¹ã‚­ãƒƒãƒ—
        if: steps.get-cooperated-issue-number.outputs.result != 'cooperated'
        with:
          # ä»˜ã‘ãŸã„ãƒã‚±ãƒƒãƒˆåã‚’é¸æŠ(jiraã®APItokenã®labelã«åˆã‚ã›ã‚‹)
          project: token-for-github
          # èª²é¡Œã‚¿ã‚¤ãƒ—ã‚’æŒ‡å®š
          issuetype: Task
          # issuesã®ã‚¿ã‚¤ãƒˆãƒ«ãŒè¦ç´„ã«ãªã‚‹ã‚ˆã†ã«è¨­å®š
          summary: ${{ github.event.issue.title }}
          # issuesã®æœ¬æ–‡ãŒèª¬æ˜ã«ãªã‚‹ã‚ˆã†ã«è¨­å®š
          description: ${{ github.event.issue.body }}

      - name: Commnet Issue Number
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'JIRA-ISSUE-NUM=${{ steps.get-cooperated-issue-number.outputs.result }}'
            })
      # - name: ã‚³ãƒ¡ãƒ³ãƒˆã¤ã‘ã¦ã¿ã‚‹
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: 'ğŸ‘‹ Thanks for reporting!'
      #       })

      # æ–¹é‡
      # 1. ã‚³ãƒ¡ãƒ³ãƒˆã‚’æœæŸ»ã—ã¦ã€JIRAã®ç´ä»˜ã‘ãŒã‚ã‚‹ã‹ã‚’æ¤œè¨¼
      # 2. JIRAã®ç´ä»˜ã‘ãŒã‚ã‚Œã°ã€çµ‚äº†
      # 3. ãªã‘ã‚Œã°ã€JIRAã®ãƒã‚±ãƒƒãƒˆç™»éŒ²

      # ã†ã‚ãƒ»ãƒ»ãƒ»ãªã‚“ã‹ã€Jiraå´ã®æƒ…å ±ã‚’GitHubä¸Šã«æŒã£ã¦ãŠã‹ãªã„ã¨ã€‚ã€‚
      # - name: Find Jira Issue
      #   uses: atlassian/gajira-find-issue-key@master
