name: Jira Cooperation Action

on:
  issues:
    types: [labeled]
  pull_request:
    branches:
      - develop

jobs:
  cooperate-issue:
    if: github.event.label.name == 'loadmap'
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Debug
        run: cat $GITHUB_EVENT_PATH

      - name: Get Comments
        uses: actions/github-script@v6
        id: return_context
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            console.log(comments, null, '\t')
            return comments
      - name: Show steps.return_context
        env:
          RETURN_CONTEXT: ${{ toJson(steps.return_context.outputs) }}
        run: echo "$RETURN_CONTEXT"

      # - name: ã‚³ãƒ¡ãƒ³ãƒˆã¤ã‘ã¦ã¿ã‚‹
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: 'ğŸ‘‹ Thanks for reporting!'
      #       })

      # æ–¹é‡
      # 1. ã‚³ãƒ¡ãƒ³ãƒˆã‚’æœæŸ»ã—ã¦ã€JIRAã®ç´ä»˜ã‘ãŒã‚ã‚‹ã‹ã‚’æ¤œè¨¼
      # 2. JIRAã®ç´ä»˜ã‘ãŒã‚ã‚Œã°ã€çµ‚äº†
      # 3. ãªã‘ã‚Œã°ã€JIRAã®ãƒã‚±ãƒƒãƒˆç™»éŒ²

      # ã†ã‚ãƒ»ãƒ»ãƒ»ãªã‚“ã‹ã€Jiraå´ã®æƒ…å ±ã‚’GitHubä¸Šã«æŒã£ã¦ãŠã‹ãªã„ã¨ã€‚ã€‚
      # - name: Find Jira Issue
      #   uses: atlassian/gajira-find-issue-key@master
